In [6]:
import pandas as pd
df=pd.read_csv('/WELFake_Dataset.csv',on_bad_lines='skip',engine='python')

In [7]:
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [8]:
df.shape

(2794, 4)

In [9]:
df.columns

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='object')

# **prepare data**

In [7]:
df=df.drop(columns=['Unnamed: 0'])

In [11]:
df=df.fillna('0')

In [9]:
df['Content']=df['title']+" "+df['text']

In [10]:
X=df['Content']
Y=df['label']

In [13]:
df.head()

,title,text,label,Content
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1,LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1,,Did they post their votes for Hillary already?,1,Did they post their votes for Hillary already?
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0,"Bobby Jindal, raised Hindu, uses story of Chri..."
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1,SATAN 2: Russia unvelis an image of its terrif...

# **Text to Number convert**

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tfidf=TfidfVectorizer(stop_words='english',max_df=0.7)

In [16]:
X_tfidf=tfidf.fit_transform(X)

# **Train and Test split**

In [17]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,Y_train,Y_test=train_test_split(X_tfidf,Y,test_size=0.2,random_state=42)

**Logistic Regression**

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
model=LogisticRegression(max_iter=1000) # max_iter= give model enough time to learn

# **Train the model**

In [23]:
model.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

# **model Evaluation**

# **importing Evaluation tools**

In [24]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

# **making predications**

In [25]:
Y_pred=model.predict(X_test) #after trained the model we must analyze how well it learned . asking the trained model to make predictions

In [26]:
accuracy=accuracy_score(Y_test,Y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.7037037037037037

## **Classification Report**

In [27]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       1.00      0.33      0.50        24
           1       0.65      1.00      0.79        30

    accuracy                           0.70        54
   macro avg       0.83      0.67      0.64        54
weighted avg       0.81      0.70      0.66        54

# **confusion matrix**

In [28]:
cm=confusion_matrix(Y_test,Y_pred)
print(cm)
#TN = 8
#Real news correctly predicted as real
#FP = 16
#Real news wrongly predicted as fake
 #FN = 0
#Fake news wrongly predicted as real → NONE (very good)
#TP = 30
 #Fake news correctly predicted as fake
 #[[TN  FP]
# [FN  TP]]

[[ 8 16]
 [ 0 30]]